### ISSUE TITLE
"h" format option not consistent

### ISSUE THREAD

**Issue by kieraneglin** [xxRockOnxx/vue2-timepicker#14]
Using latest master, setting format to `H:mm` removes the leading zeros from the hours column, but when a time is selected it appears in the input with leading zeros.

Furthermore, once you've selected an hour, it doesn't appear as being selected in the dropdown.

Thank you for the fork!

**Comment by xxRockOnxx** [comment]
I tried it in playground but it works?

**Comment by kieraneglin** [comment]
Hmm, I'll take a look at why it's failing in my case.

Unrelated, but what was the reason for removing the `@change` event?  Getting a full list of the time data was a very useful feature.

**Comment by kieraneglin** [comment]
@xxRockOnxx My apologies!  I misspoke.  I wasn't using `H`, I was using `h`.  This is also not working in the playground.

Unfortunately, I can't edit the title.  If you'd like me to create a new issue, I certainly can!

**Comment by xxRockOnxx** [comment]
I see. I'll try to fix this tonight

**Comment by xxRockOnxx** [comment]
@kieraneglin can you please confirm? I'll re-open this if not. Sorry for the delay, it's holiday season.

**Comment by kieraneglin** [comment]
@xxRockOnxx It seems to work great!  Thank you
