### ISSUE TITLE
update display user

### ISSUE THREAD

**Issue by thiagoanselmo** [xxRockOnxx/vue2-timepicker#18]
I have to boxes. If i change the first i add 3 hours to the second box. The value is correct but the display time doesn't update after the component is once created.

**Comment by xxRockOnxx** [comment]
i don't understand the problem. Can you please provide the steps to reproduce, what you expect to happen, and what actually happens?

**Comment by xxRockOnxx** [comment]
@thiagoanselmo did you solved it? Will close this soon.
