### ISSUE TITLE
Change event not firing

### ISSUE THREAD

**Issue by netgfx** [xxRockOnxx/vue2-timepicker#26]
### What are the steps to reproduce the bug?

Simple setup: 
```
<vue-timepicker v-bind:hide-clear-button=true v-model="fromTimeValue" id="fromTimeInput" @change="onTimeFromSelect" class="form-control col-12" @focus="minimizeLabelSelect" @click="minimizeLabelSelect" @blur="maximizeLabelSelect" format="hh:mm A"></vue-timepicker>
```
but neither the `click` or `change` events fire (the methods exist)

Any ideas?

**Comment by lemuelflores** [comment]
Can you try installing from this commit: https://github.com/xxRockOnxx/vuejs-timepicker/commit/bb595be0c1129e7fa1363d84362a3d272d8e9932

if it worked, most likely it's bc of the recent PR. I'll try to fix it afterwards.
