### ISSUE TITLE
webpack issue

### ISSUE THREAD

**Issue by pepf** [xxRockOnxx/vue2-timepicker#3]
Hey man, thanks for making a fork in an effort to maintain this library :)
I was planning on making a fork as well, but perhaps I can send in some PR's for issues I encountered.

One of the main things that struc me about the lib is the lack of a proper build (see https://github.com/phoenixwong/vue2-timepicker/issues/15 ) but this guy seems to have [nailed that one down already](https://github.com/beijaflor/vue2-timepicker/commit/2ea57449a940d670d15501e6ff617e4884281486) If that one is fixed and the dist is added to the package.json, this thing can actually be npm installed without errors :)

**Comment by xxRockOnxx** [comment]
Yea, I'll check it out. I saw that one before. It's just that I have a local copy of my repo that I point to instead of `npm install` that's why I didn't do it hahaha.

**Comment by xxRockOnxx** [comment]
Fixed 2c0c64341447e855891deade3e3bfe2f332470a1
