### ISSUE TITLE
How to npm install your fork instead of the original package?

### ISSUE THREAD

**Issue by jobelenus** [xxRockOnxx/vue2-timepicker#5]
I saw your comment over there. And I'm having a problem loading the component. I'm getting:

`Failed to mount component: template or render function not defined.

found in

---> <VueTimepicker>
       <Root>`

Wondering if your fork will fix this problem, along with other things. I'm on vue 2.4.4.

**Comment by xxRockOnxx** [comment]
I uploaded this repo for a while now. I think I did not compiled one for `dist`. Try importing the one at `src` instead temporarily. I'll try fixing this tomorrow for real now. #3 asked me about this actually but I forgot about it because of work.

**Comment by jobelenus** [comment]
OK. Did you encounter my error? Could it be some sort of setup problem?
require problem? webpack problem?

**Comment by xxRockOnxx** [comment]
Maybe because you are not importing the file from `src` folder.

If you only did `import VueTimepicker from 'vue2-timepicker'` that will import the `dist` file or whatever the `index` is set on the package.json of a package.

**Comment by jobelenus** [comment]
But if `dist` is built from `src` shouldn't it have everything?

**Comment by xxRockOnxx** [comment]
Yes, but if it was not built properly then the output will not be a proper one hence why many people have problems importing the `dist` file.

When I forked this I did not compiled/build it. My goal was to add a `disabled` values not fix the error. And like I said, I'd just import the `src` file not the `dist`

**Comment by xxRockOnxx** [comment]
Fixed 2c0c64341447e855891deade3e3bfe2f332470a1

try doing import again like in the documentation. Please confirm so I can close this

**Comment by jobelenus** [comment]
?? i don't even have yours installed via npm. is there a way to do that??

**Comment by jobelenus** [comment]
No. I don't know how to install your package via NPM. How can I do that?

**Comment by xxRockOnxx** [comment]
See this: https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

**Comment by jacurtis** [comment]
This issue is painful to read through. @jobelenus is simply looking for how to install this package through npm.

This is how you install it:

    npm install git+https://github.com/xxRockOnxx/vue2-timepicker.git --save

or via Yarn

    yarn add git+https://github.com/xxRockOnxx/vue2-timepicker.git

**Comment by jacurtis** [comment]
Submitted a PR to make life a little easier for anyone else who finds this package, so they know how to install this one, over installing the non-maintained version which this repo was forked from.

_Thank you to @xxRockOnxx for maintaining this package for us._
