### ISSUE TITLE
If you select a number greater than 12, it will not be highlighted

### ISSUE THREAD

**Issue by RVisal** [xxRockOnxx/vue2-timepicker#9]
Hi

If you select a number greater than 12, it will not be highlighted.

**format="HH:mm"**

When selected 22, but value is 10.
![Bug](https://user-images.githubusercontent.com/12168423/33152041-a2e3962a-cfeb-11e7-9601-07185283a080.png)

**Comment by xxRockOnxx** [comment]
Can you please try the `fix/hour-select` branch before I merge? Please run the following when installing

`npm install git://github.com:xxRockOnxx/vue2-timepicker.gitt#fix/hour-select --save-dev`

**Comment by RVisal** [comment]
It's work, Thank you!
![github](https://user-images.githubusercontent.com/12168423/33305420-1a5fc124-d41f-11e7-9419-b58a66b6c9c8.png)

**Comment by xxRockOnxx** [comment]
Note: Please install from the master again now. I merged and deleted the branch.
